var deviceDataId=0,userIddeviceDataId=0,pageSize=100,times=new Date,intervalIds,shefenId;$(function(){$(document).ready(function(){initSpline1();initUserDataChat("18FE349EA886")})});function userClick(){initUserDataChat($("#tempId1").val())}
function initUserDataChat(b){try{shefenId=b,userIddeviceDataId=0,intervalIds&&clearInterval(intervalIds),jQuery.ajax({url:"../device/deviceshowchatbyuser.htm",data:{deviceDataId:userIddeviceDataId,pageSize:pageSize,shefenId:shefenId},type:"POST",beforeSubmit:function(){pingLuning2=!0},error:function(a){pingLuning2=!1;initDatas([],[],[],[],[],[])},success:function(a){pingLuning2=!1;try{var b=[],c=[],e=[],k=[],g=[],d=[];if(a&&a.deviceDatas)for(var l,h=0;h<a.deviceDatas.length;h++){l=(new Date(a.deviceDatas[h].createTime)).getTime();
if(0==h&&3E5<(new Date).getTime()-l){userIddeviceDataId=a.deviceDatas[a.deviceDatas.length-1].deviceDataId;break}b.push({x:l,y:a.deviceDatas[h].delta});c.push({x:l,y:a.deviceDatas[h].theta});e.push({x:l,y:a.deviceDatas[h].lowAlpha});k.push({x:l,y:a.deviceDatas[h].highAlpha});g.push({x:l,y:a.deviceDatas[h].lowBeta});d.push({x:l,y:a.deviceDatas[h].highBeta});userIddeviceDataId=a.deviceDatas[h].deviceDataId}initDatas(b,c,e,k,g,d)}catch(m){}}})}catch(a){}}
function initDatas(b,a,f,c,e,k){var g=times.getTime(),d;if(0==b.length)for(d=b.length;d<pageSize;d++)b.push({x:g-1E3*(pageSize-d),y:0});if(0==a.length)for(d=a.length;d<pageSize;d++)a.push({x:g-1E3*(pageSize-d),y:0});if(0==f.length)for(d=f.length;d<pageSize;d++)f.push({x:g-1E3*(pageSize-d),y:0});if(0==c.length)for(d=c.length;d<pageSize;d++)c.push({x:g-1E3*(pageSize-d),y:0});if(0==e.length)for(d=e.length;d<pageSize;d++)e.push({x:g-1E3*(pageSize-d),y:0});if(0==k.length)for(d=k.length;d<pageSize;d++)k.push({x:g-
1E3*(pageSize-d),y:0});spline2("containerUser",b,a,f,c,e,k)}var chartCurr,pingLuning=!1;
function avgChatData(b){chartCurr=b;1!=pingLuning&&jQuery.ajax({url:"../device/deviceshowchat.htm",data:{deviceDataId:deviceDataId,pageSize:pageSize},type:"POST",beforeSubmit:function(){pingLuning=!0},error:function(a){pingLuning=!1},success:function(a){pingLuning=!1;try{if(a&&a.deviceDatas)for(var b,c=0;c<a.deviceDatas.length;c++)b=(new Date(a.deviceDatas[c].createTime)).getTime(),chartCurr.series[0].addPoint([b,a.deviceDatas[c].attention],!0,!0),chartCurr.series[1].addPoint([b,a.deviceDatas[c].meditation],
!0,!0),deviceDataId=a.deviceDatas[c].deviceDataId}catch(e){}}})}
function initSpline1(){jQuery.ajax({url:"../device/deviceshowchat.htm",data:{deviceDataId:deviceDataId,pageSize:pageSize},type:"POST",beforeSubmit:function(){pingLuning=!0},error:function(b){pingLuning=!1;initttt([],[])},success:function(b){pingLuning=!1;try{var a=[],f=[];if(b&&b.deviceDatas)for(var c,e=0;e<b.deviceDatas.length;e++){c=(new Date(b.deviceDatas[e].createTime)).getTime();deviceDataId=b.deviceDatas[e].deviceDataId;if(0==e&&3E5<(new Date).getTime()-c){deviceDataId=b.deviceDatas[b.deviceDatas.length-
1].deviceDataId;break}a.push({x:c,y:b.deviceDatas[e].attention});f.push({x:c,y:b.deviceDatas[e].meditation})}initttt(a,f)}catch(k){}}})}function initttt(b,a){if(19>b.length){var f=[],c=times.getTime(),e;for(e=pageSize;0<=e;e--)f.push({x:c-1E3*e,y:0});a=b=f}spline1("container",b,a)}var chartCurr2,pingLuning2=!1;
function userChatData(b){chartCurr2=b;1!=pingLuning2&&jQuery.ajax({url:"../device/deviceshowchatbyuser.htm",data:{deviceDataId:userIddeviceDataId,pageSize:pageSize,shefenId:shefenId},type:"POST",beforeSubmit:function(){pingLuning2=!0},error:function(a){pingLuning2=!1},success:function(a){pingLuning2=!1;try{if(a&&a.deviceDatas)for(var b,c=0;c<a.deviceDatas.length;c++)b=(new Date(a.deviceDatas[c].createTime)).getTime(),chartCurr2.series[0].addPoint([b,a.deviceDatas[c].delta],!0,!0),chartCurr2.series[1].addPoint([b,
a.deviceDatas[c].theta],!0,!0),chartCurr2.series[2].addPoint([b,a.deviceDatas[c].lowAlpha],!0,!0),chartCurr2.series[3].addPoint([b,a.deviceDatas[c].highAlpha],!0,!0),chartCurr2.series[4].addPoint([b,a.deviceDatas[c].lowBeta],!0,!0),chartCurr2.series[5].addPoint([b,a.deviceDatas[c].highBeta],!0,!0),userIddeviceDataId=a.deviceDatas[c].deviceDataId}catch(e){}}})}
function spline1(b,a,f){return new Highcharts.Chart({chart:{renderTo:b,type:"spline",animation:Highcharts.svg,marginRight:10,events:{load:function(){var a=this;setInterval(function(){avgChatData(a)},1E3)}}},title:{text:"\u8111\u7535\u6ce2"},xAxis:{type:"datetime",tickPixelInterval:150,labels:{enabled:!0},tickLength:0},yAxis:{title:{text:"\u6ce2\u957f"},plotLines:[{value:0,width:1,color:"#808080"}]},credits:{enabled:!1},tooltip:{formatter:function(){return"<b>"+this.series.name+"</b><br/>"+Highcharts.dateFormat("%Y-%m-%d %H:%M:%S",
this.x)+"<br/>"+Highcharts.numberFormat(this.y,2)}},legend:{enabled:!0},exporting:{enabled:!1},series:[{name:"\u4e13\u6ce8\u5ea6",marker:{enabled:!1},data:a},{name:"\u653e\u677e\u5ea6",marker:{enabled:!1,radius:5},data:f}]})}
function spline2(b,a,f,c,e,k,g){return new Highcharts.Chart({chart:{renderTo:b,type:"spline",animation:Highcharts.svg,marginRight:10,events:{load:function(){var a=this;intervalIds=setInterval(function(){userChatData(a)},1E3)}}},title:{text:"\u8111\u7535\u6ce2"},xAxis:{type:"datetime",tickPixelInterval:150,labels:{enabled:!0},tickLength:0},yAxis:{title:{text:"\u6ce2\u957f"},plotLines:[{value:0,width:1,color:"#808080"}]},credits:{enabled:!1},tooltip:{formatter:function(){return"<b>"+this.series.name+
"</b><br/>"+Highcharts.dateFormat("%Y-%m-%d %H:%M:%S",this.x)+"<br/>"+Highcharts.numberFormat(this.y,2)}},legend:{enabled:!0},exporting:{enabled:!1},series:[{name:"\u03b4",marker:{enabled:!1},data:a},{name:"\u03b8",marker:{enabled:!1,radius:5},data:f},{name:"low-\u03b1",marker:{enabled:!1,radius:5},data:c},{name:"high-\u03b1",marker:{enabled:!1,radius:5},data:e},{name:"low-\u03b2",marker:{enabled:!1,radius:5},data:k},{name:"high-\u03b2",marker:{enabled:!1,radius:5},data:g}]})};