var deviceDataId=0,userIddeviceDataId=0,pageSize=100,times=new Date,intervalIds,shefenId;$(function(){$(document).ready(function(){window.slots={};window.c=document.getElementById("loadingProgress");window.ctx=c.getContext("2d");window.ctx2=document.getElementById("loadingProgress2").getContext("2d");initSpline1();initUserDataChat("18FE349EA886");deviceshowchatbyalluser()})});function userClick(){initUserDataChat($("#tempId1").val())}
function initUserDataChat(a){try{shefenId=a,userIddeviceDataId=0,intervalIds&&clearInterval(intervalIds),jQuery.ajax({url:"../device/deviceshowchatbyuser.htm",data:{deviceDataId:userIddeviceDataId,pageSize:pageSize,shefenId:shefenId},type:"POST",beforeSubmit:function(){pingLuning2=!0},error:function(a){pingLuning2=!1;initDatas([],[],[],[],[],[])},success:function(a){pingLuning2=!1;try{var e=[],f=[],d=[],h=[],k=[],l=[],m=[];if(a&&a.deviceDatas){var g=0;20<a.deviceDatas.length&&(g=a.deviceDatas.length-
20);for(var n=1;g<a.deviceDatas.length;g++)m.push(n++ +""),(new Date(a.deviceDatas[g].createTime)).getTime(),e.push(a.deviceDatas[g].delta),f.push(a.deviceDatas[g].theta),d.push(a.deviceDatas[g].lowAlpha),h.push(a.deviceDatas[g].highAlpha),k.push(a.deviceDatas[g].lowBeta),l.push(a.deviceDatas[g].highBeta),userIddeviceDataId=a.deviceDatas[g].deviceDataId}initDatas(m,e,f,d,h,k,l)}catch(p){}}})}catch(b){}}function initDatas(a,b,e,f,d,h,k){spline2(a,b,e,f,d,h,k)}var chartCurr,pingLuning=!1;
function initSpline1(){jQuery.ajax({url:"../device/deviceshowchat.htm",data:{deviceDataId:deviceDataId,pageSize:pageSize},type:"POST",beforeSubmit:function(){pingLuning=!0},error:function(a){pingLuning=!1;spline1([],[],[])},success:function(a){pingLuning=!1;try{var b=[],e=[],f=[];if(a&&a.deviceDatas){var d=0;20<a.deviceDatas.length&&(d=a.deviceDatas.length-20);for(var h=1;d<a.deviceDatas.length;d++)f.push(h++ +""),(new Date(a.deviceDatas[d].createTime)).getTime(),deviceDataId=a.deviceDatas[d].deviceDataId,
b.push(a.deviceDatas[d].attention),e.push(a.deviceDatas[d].meditation);0<a.deviceDatas.length&&(loadingProgressAttention(a.deviceDatas[a.deviceDatas.length-1].attention),loadingProgressMeditation(a.deviceDatas[a.deviceDatas.length-1].meditation))}spline1(f,b,e)}catch(k){}}})}
function deviceshowchatbyalluser(){try{jQuery.ajax({url:"../device/deviceshowchatbyalluser.htm",data:{},type:"POST",beforeSubmit:function(){},error:function(a){},success:function(a){try{if(a&&a.deviceDataVOs)for(var b=0;b<a.deviceDataVOs.length;b++)$("#delta_"+a.deviceDataVOs[b].shefenId).html(a.deviceDataVOs[b].delta),$("#theta_"+a.deviceDataVOs[b].shefenId).html(a.deviceDataVOs[b].theta),$("#low_alpha_"+a.deviceDataVOs[b].shefenId).html(a.deviceDataVOs[b].lowAlpha),$("#high_alpha_"+a.deviceDataVOs[b].shefenId).html(a.deviceDataVOs[b].highAlpha),
$("#low_beta_"+a.deviceDataVOs[b].shefenId).html(a.deviceDataVOs[b].lowBeta),$("#high_beta_"+a.deviceDataVOs[b].shefenId).html(a.deviceDataVOs[b].highBeta),$("#attention_"+a.deviceDataVOs[b].shefenId).html(a.deviceDataVOs[b].attention),$("#meditation_"+a.deviceDataVOs[b].shefenId).html(a.deviceDataVOs[b].meditation)}catch(e){}}})}catch(a){}}var chartCurr2,pingLuning2=!1;
function spline1(a,b,e){var f=echarts.init(document.getElementById("tu1"));option={tooltip:{trigger:"axis"},legend:{data:["Attention","Meditation"]},grid:{left:"3%",right:"4%",bottom:"10%",containLabel:!0},xAxis:[{type:"category",boundaryGap:!1,data:a}],yAxis:[{type:"value"}],dataZoom:[{type:"inside",start:0,end:100},{start:0,end:100}],series:[{name:"Attention",type:"line",stack:"\u603b\u91cf",areaStyle:{normal:{}},data:b},{name:"Meditation",type:"line",stack:"\u603b\u91cf",areaStyle:{normal:{}},
data:e}],color:["#FF6C60","#23B7E5"]};f.setOption(option,!0)}
function spline2(a,b,e,f,d,h,k){var l=echarts.init(document.getElementById("bar"));option={tooltip:{trigger:"axis"},legend:{data:"Delta;Theta;Low Alpha;Hight Alpha;Low beta;Hight beta".split(";")},grid:{left:"3%",right:"4%",bottom:"10%",containLabel:!0},xAxis:[{type:"category",boundaryGap:!1,data:a}],yAxis:[{type:"value"}],dataZoom:[{type:"inside",start:0,end:100},{start:0,end:100}],series:[{name:"Delta",type:"line",stack:"\u603b\u91cf",areaStyle:{normal:{}},data:b},{name:"Theta",type:"line",stack:"\u603b\u91cf",
areaStyle:{normal:{}},data:e},{name:"Low Alpha",type:"line",stack:"\u603b\u91cf",areaStyle:{normal:{}},data:f},{name:"Hight Alpha",type:"line",stack:"\u603b\u91cf",areaStyle:{normal:{}},data:d},{name:"Low beta",type:"line",stack:"\u603b\u91cf",areaStyle:{normal:{}},data:h},{name:"Hight beta",type:"line",stack:"\u603b\u91cf",areaStyle:{normal:{}},data:k}],color:"#FF6C60 #23B7E5 #FF6C60 #FCB322 #39B2A9 #caa3da".split(" ")};l.setOption(option,!0)};